### ISSUE TITLE
Is this gem still maintained?

### ISSUE THREAD

**Issue by jgmontoya** [bumi/lnrpc#25]
First of all, thank you for this, it's great!

Will there be further releases to catch up to LND? There have been some major and minor updates to LND since the last release and I'm not quite sure how breaking they are with respect to this gem. Is there a good way to figure out the extent of the possible 'incompatibility' between lnrpc v14.3.1 and lnd v0.15.5-beta?

Should we look for alternatives?

**Comment by bumi** [comment]
@jgmontoya thanks for the ping. I'll do a release for the new LND versions

**Comment by bumi** [comment]
just updated the mater to v0.15.5

**Comment by jgmontoya** [comment]
Wow amazing, thank you!!

**Comment by iraszl** [comment]
Thanks @bumi ! 🙌
