### ISSUE TITLE
issues with subscribe_invoices client shortcut

### ISSUE THREAD

**Issue by ryan-lingle** [bumi/lnrpc#7]
The following appears to be working just fine:
```ruby
request = Lnrpc::InvoiceSubscription.new(add_index: 1)
lnd.grpc_client.subscribe_invoices(request) do |e|
  puts e.payment_request
end
```

whereas the client shortcut version of this is not (I could be doing something wrong):
```ruby
lnd.subscribe_invoices(add_index: 1) do |e|
  puts e.payment_request
end
```

**Comment by bumi** [comment]
ahh, cool. I haven't tested the subscription features, yet... thanks again for reporting it! 

it seems I am missing a `&block` here: 
https://github.com/bumi/lnrpc/blob/master/lib/lnrpc/client.rb#L65

should probably be: 
`self.grpc_client.send(m, *args, &block)`

**Comment by bumi** [comment]
I've pushed this commit: https://github.com/bumi/lnrpc/blob/master/lib/lnrpc/client.rb#L65 
but I will probably only release a new version once I have finally a proper test setup. 
Can you test it from master if it works for you?

**Comment by ryan-lingle** [comment]
Tested and it works great!
