### ISSUE TITLE
rake assets:precompile breaks with no tls.cert

### ISSUE THREAD

**Issue by ryan-lingle** [bumi/lnrpc#9]
I was trying to host a small app using this gem on Heroku and during the build ran into this error:
```
Running: rake assets:precompile
remote:        rake aborted!
remote:        Errno::ENOENT: No such file or directory @ rb_sysopen - /app/.lnd/tls.cert
remote:        /tmp/build_d0e548cbc598816263de2c4d04b9565e/vendor/bundle/ruby/2.4.0/gems/lnrpc-0.5.2/lib/lnrpc/client.rb:34:in `read'
```
The code in question is this line:
```ruby
elsif File.exists?(::File.expand_path(options[:credentials_path] || DEFAULT_CREDENTIALS_PATH))
   self.credentials = ::File.read(::File.expand_path(options[:credentials_path] || DEFAULT_CREDENTIALS_PATH))
else
```

Even though that block won't ever be touched by the application, the precompile has to assume it will? Might have to be something where I have to edit the gem for my project specifically, but was wondering if you had a potential fix in mind?

Either way thanks!

**Comment by ryan-lingle** [comment]
I suppose I could just throw a dummy tls.cert in the directory. A little hacky, but could do the trick.

**Comment by bumi** [comment]
yeah, guess loading files by default is not a good idea that should probably be removed.

**Comment by bumi** [comment]
if you pass in a `credentials` and a `macaroon` option it should do the trick and not fallback to a default file it tries to load. 
if you use the latest version from master.

**Comment by ryan-lingle** [comment]
Awesome, thanks!
